// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositoryy;

#nullable disable

namespace Repositoryy.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260323131424_SeedDataUpdate")]
    partial class SeedDataUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Volunteer.Entities.MyVolunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("Volunteers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "yael@example.com",
                            FirstName = "Yael",
                            LastName = "Gutman",
                            Password = "pass1",
                            Role = "user",
                            SkillId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "yehudit@example.com",
                            FirstName = "Yehudit",
                            LastName = "Vaiss",
                            Password = "pass2",
                            Role = "user",
                            SkillId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "noa@example.com",
                            FirstName = "Noa",
                            LastName = "Levi",
                            Password = "pass3",
                            Role = "user",
                            SkillId = 3
                        },
                        new
                        {
                            Id = 4,
                            Email = "michal@example.com",
                            FirstName = "Michal",
                            LastName = "Cohen",
                            Password = "pass4",
                            Role = "admin",
                            SkillId = 1
                        },
                        new
                        {
                            Id = 5,
                            Email = "tamar@example.com",
                            FirstName = "Tamar",
                            LastName = "Aharoni",
                            Password = "pass5",
                            Role = "user",
                            SkillId = 4
                        },
                        new
                        {
                            Id = 6,
                            Email = "rivka@example.com",
                            FirstName = "Rivka",
                            LastName = "Shwartz",
                            Password = "pass6",
                            Role = "user",
                            SkillId = 5
                        },
                        new
                        {
                            Id = 7,
                            Email = "sarah@example.com",
                            FirstName = "Sarah",
                            LastName = "Gold",
                            Password = "pass7",
                            Role = "user",
                            SkillId = 2
                        },
                        new
                        {
                            Id = 8,
                            Email = "esther@example.com",
                            FirstName = "Esther",
                            LastName = "Katz",
                            Password = "pass8",
                            Role = "user",
                            SkillId = 3
                        },
                        new
                        {
                            Id = 9,
                            Email = "avigail@example.com",
                            FirstName = "Avigail",
                            LastName = "Friedman",
                            Password = "pass9",
                            Role = "user",
                            SkillId = 4
                        },
                        new
                        {
                            Id = 10,
                            Email = "leah@example.com",
                            FirstName = "Leah",
                            LastName = "Stern",
                            Password = "pass10",
                            Role = "user",
                            SkillId = 5
                        });
                });

            modelBuilder.Entity("Volunteer.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Baking"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cleaning"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Teaching"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gardening"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Coding"
                        });
                });

            modelBuilder.Entity("Volunteer.Entities.MyVolunteer", b =>
                {
                    b.HasOne("Volunteer.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId");

                    b.Navigation("Skill");
                });
#pragma warning restore 612, 618
        }
    }
}
