// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositoryy;

#nullable disable

namespace Repositoryy.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260323135959_FinalManyToManyUpdate")]
    partial class FinalManyToManyUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyVolunteerSkill", b =>
                {
                    b.Property<int>("SkillsId")
                        .HasColumnType("int");

                    b.Property<int>("VolunteersId")
                        .HasColumnType("int");

                    b.HasKey("SkillsId", "VolunteersId");

                    b.HasIndex("VolunteersId");

                    b.ToTable("MyVolunteerSkill");

                    b.HasData(
                        new
                        {
                            SkillsId = 1,
                            VolunteersId = 1
                        },
                        new
                        {
                            SkillsId = 2,
                            VolunteersId = 2
                        },
                        new
                        {
                            SkillsId = 3,
                            VolunteersId = 2
                        },
                        new
                        {
                            SkillsId = 3,
                            VolunteersId = 3
                        },
                        new
                        {
                            SkillsId = 1,
                            VolunteersId = 4
                        },
                        new
                        {
                            SkillsId = 4,
                            VolunteersId = 5
                        },
                        new
                        {
                            SkillsId = 5,
                            VolunteersId = 6
                        },
                        new
                        {
                            SkillsId = 2,
                            VolunteersId = 7
                        },
                        new
                        {
                            SkillsId = 3,
                            VolunteersId = 8
                        },
                        new
                        {
                            SkillsId = 4,
                            VolunteersId = 9
                        },
                        new
                        {
                            SkillsId = 5,
                            VolunteersId = 10
                        });
                });

            modelBuilder.Entity("Volunteer.Entities.MyVolunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Volunteers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1995, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "yael@example.com",
                            FirstName = "Yael",
                            LastName = "Gutman",
                            Password = "pass1",
                            PhoneNumber = "050-1234561",
                            Role = "user"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1998, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "yehudit@example.com",
                            FirstName = "Yehudit",
                            LastName = "Vaiss",
                            Password = "pass2",
                            PhoneNumber = "052-1234562",
                            Role = "user"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1992, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "noa@example.com",
                            FirstName = "Noa",
                            LastName = "Levi",
                            Password = "pass3",
                            PhoneNumber = "054-1234563",
                            Role = "user"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1990, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "michal@example.com",
                            FirstName = "Michal",
                            LastName = "Cohen",
                            Password = "pass4",
                            PhoneNumber = "053-1234564",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1997, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tamar@example.com",
                            FirstName = "Tamar",
                            LastName = "Aharoni",
                            Password = "pass5",
                            PhoneNumber = "058-1234565",
                            Role = "user"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1994, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rivka@example.com",
                            FirstName = "Rivka",
                            LastName = "Shwartz",
                            Password = "pass6",
                            PhoneNumber = "050-1234566",
                            Role = "user"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1996, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sarah@example.com",
                            FirstName = "Sarah",
                            LastName = "Gold",
                            Password = "pass7",
                            PhoneNumber = "052-1234567",
                            Role = "user"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1993, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "esther@example.com",
                            FirstName = "Esther",
                            LastName = "Katz",
                            Password = "pass8",
                            PhoneNumber = "054-1234568",
                            Role = "user"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1999, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "avigail@example.com",
                            FirstName = "Avigail",
                            LastName = "Friedman",
                            Password = "pass9",
                            PhoneNumber = "053-1234569",
                            Role = "user"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1991, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "leah@example.com",
                            FirstName = "Leah",
                            LastName = "Stern",
                            Password = "pass10",
                            PhoneNumber = "058-1234560",
                            Role = "user"
                        });
                });

            modelBuilder.Entity("Volunteer.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Baking"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cleaning"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Teaching"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gardening"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Coding"
                        });
                });

            modelBuilder.Entity("MyVolunteerSkill", b =>
                {
                    b.HasOne("Volunteer.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Volunteer.Entities.MyVolunteer", null)
                        .WithMany()
                        .HasForeignKey("VolunteersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
